### ISSUE TITLE
Implement PrimInt::from_le from_be and to_be to_le

### ISSUE THREAD

**Issue by kaidokert** [kaidokert/fixed-bigint-rs#10]
Code in https://github.com/kaidokert/fixed-bigint-rs/blob/main/src/fixeduint.rs#L1232

**Comment by Onyinye91-ctrl** [comment]
@kaidokert i am interested in this issue. But i do really want to understand what to do. You mean I should replace `from_le` with``to_le` and `from_be` with `to_be in the link attached?

**Comment by kaidokert** [comment]
Not exactly. The correct byte swapping needs to be implemented, as per the spec: https://docs.rs/num-traits/0.2.14/num_traits/int/trait.PrimInt.html#tymethod.from_be

A good test case:` FixedUInt<u32,1>::from_be()`, `FixedUInt<u8,4>::from_be()` and builtin `u32::from_be()` should all yield identical results.

**Comment by Onyinye91-ctrl** [comment]
Okay, i just checked the link shared, so i should copy and paste the examples in todo?
